### ISSUE TITLE
DNS Lookup

### ISSUE THREAD

**Issue by joe-weizhou-wang** [OscarZhou0107/db-in-k8s#1]
Currently, the TCP connection only accepts numerical IPs. If we change the numerical IP to their domain name, e.g. 127.0.0.1 -> localhost, then there will be errors. Especially for the connections between dbproxys and the scheduler.

Possibly lines to modify: o2versioner/src/util/conf.rs:178 (but not sure if there are other locations needed to be changed as well)
A utility to perform DNS lookup in Rust: https://docs.rs/dns-lookup/latest/dns_lookup/

**Comment by joe-weizhou-wang** [comment]
To test, replace all "127.0.0.1" with "localhost" in the .toml file:
----------------------------------------------------------------------
[scheduler]
addr = "localhost:2077"
admin_addr = "localhost:9999"
#disable_early_release = true
#disable_single_read_optimization = true

[sequencer]
addr = "localhost:19876"

[[dbproxy]]
addr = "localhost:38875"
#sql_conf = "host=34.70.104.125 port=5432 dbname=tpcw user=postgres password=Abc@123"
[dbproxy.db_mock_latency]
begintx = {mean = 30, stddev = 10}
endtx = {mean = 20, stddev = 10}
read = {mean = 20, stddev = 10}
write = {mean = 30, stddev = 10}

[[dbproxy]]
addr = "localhost:38876"
#sql_conf = "host=34.69.18.204 port=5432 dbname=tpcw user=postgres password=Abc@123"
[dbproxy.db_mock_latency]
begintx = {mean = 30, stddev = 10}
endtx = {mean = 20, stddev = 10}
read = {mean = 20, stddev = 10}
write = {mean = 30, stddev = 10}

**Comment by OscarZhou0107** [comment]
db proxies changed using lookupDNS while scheduler and sequencer use string replace.
