### ISSUE TITLE
Send Pod ID to Scheduler

### ISSUE THREAD

**Issue by joe-weizhou-wang** [OscarZhou0107/db-in-k8s#4]
After a new Pod is created and is ready to connect, it needs to send its Replica ID to the scheduler. After the scheduler receives the new ID, it needs to start the connection to the new Replica.

Probably through TCP, and the scheduler needs to connect to the new proxy through argv, rather than .toml

**Comment by joe-weizhou-wang** [comment]
The Replica ID can be extracted from the $HOSTNAME env

**Comment by joe-weizhou-wang** [comment]
- One possible approach is to let the new proxy send a message to the admin with its Replica ID.
- The second approach is to turn DB proxy into a TCP client, and the scheduler into a TCP server. But in this way, the scheduler needs to somehow actively pull for new TCP connections from new proxies (probably use a listening thread? Or can we use interrupt?).

**Comment by joe-weizhou-wang** [comment]
**To-Do-List**
--------------------Rust-------------------------
1. Create multiple .toml files for each replicated proxies
2. Netcat 需要传进去一个replica ID， scheduler需要根据ID来选择对应的IP
3. 把perf的latency结果存到file里

--------------------K8s--------------------------
1. 尝试在proxy的pod里连admin，block/unblock，手动把新的proxy连到scheduler上
2. 等Rust那边的2完成后，尝试自动连scheduler：先用kubectl手动，再用HPA自动
3. 研究用除了cpu和memory以外的metrics

**Comment by spencerSunLingWei** [comment]
K8s part 1 - done
1. set the desired conf_dbproxy2.toml content to replicate.toml
2. connect admin port using kubectl exec -it commands in scheduler pod
3. achieved scale up one dbproxy (2 -> 3), connected through admin port, new dbproxy connected to schedular and start running workload
