### ISSUE TITLE
Dispatcher Keeps Running After Block

### ISSUE THREAD

**Issue by joe-weizhou-wang** [OscarZhou0107/db-in-k8s#5]
**After issuing "block" from admin, the dispatcher keeps sending its outstanding queries to dbproxies.**

**1. Possible Reasons**
![image](https://user-images.githubusercontent.com/59983226/221434674-e5205ac6-ee52-4d33-8128-779a6964882d.png)
As can be seen, after block is issued, the dispatcher/transceiver keeps pushing items into the FIFO queue, which are transactions from the dispatcher.
![image](https://user-images.githubusercontent.com/59983226/221434798-8a83ed2c-4d4e-47e0-9a89-564529edb018.png)

**2. Potential Fixes**
Check if the system has been blocked before pushing items to the queue and sending them to dbproxies (transceiver.rs: Lines 191 and 196).
![image](https://user-images.githubusercontent.com/59983226/221434883-e9ef69d2-bdf8-44e3-9b0e-ecb2f842111e.png)

**Comment by OscarZhou0107** [comment]
solved with https://github.com/OscarZhou0107/db-in-k8s/commit/152849f34b1eeed89c79ca7b9c54cdbeb65eae5f
